[build]
providers = ["python"]

[build.env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
# Force headless mode for graphics libraries  
DISPLAY = ""
QT_QPA_PLATFORM = "offscreen"
MPLBACKEND = "Agg"
# OpenCV headless configuration
OPENCV_IO_ENABLE_OPENEXR = "false"
OPENCV_IO_ENABLE_JASPER = "false"
# Disable GUI-related imports
SDL_VIDEODRIVER = "dummy"

[phases.setup]
# HEADLESS ONLY - Remove OpenGL libraries that cause libGL.so.1 errors
aptPkgs = [
    "libglib2.0-0",
    "libsm6",
    "libxext6", 
    "libxrender1",
    "libgomp1"
]

# CRITICAL: Fix dependencies after pip install completes
[phases.postInstall]
dependsOn = ["install"]  
cmds = [
    "echo '🔧 NIXPACKS: Post-install fixes for PaddleX headless deployment...'",
    # Fix OpenCV - remove GUI version, keep headless only
    ". /opt/venv/bin/activate && pip uninstall -y opencv-python opencv-contrib-python || echo 'OpenCV GUI packages not found'",
    ". /opt/venv/bin/activate && pip install --force-reinstall opencv-contrib-python-headless>=4.5.0",
    # Ensure PaddleX OCR dependencies are installed
    ". /opt/venv/bin/activate && pip install 'paddlex[ocr]>=3.0.0' --force-reinstall",
    "echo '✅ NIXPACKS: Dependency fixes completed'",
    ". /opt/venv/bin/activate && python -c 'import cv2; print(f\"✅ OpenCV {cv2.__version__} verified in headless mode\")' || echo '❌ OpenCV verification failed'",
    ". /opt/venv/bin/activate && python -c 'from paddlex import create_pipeline; print(\"✅ PaddleX OCR dependencies verified\")' || echo '❌ PaddleX verification failed'"
]

[start]
cmd = "python main.py"