[build]
providers = ["python"]

[build.env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[phases.setup]
aptPkgs = [
    # Only minimal dependencies needed for PaddleOCR headless
    "libjpeg-dev",
    "libpng-dev",
    "libtiff-dev"
]


[start]
cmd = "python main.py"