[build]
providers = ["python"]

[build.env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
# Force headless mode for graphics libraries  
DISPLAY = ""
QT_QPA_PLATFORM = "offscreen"
MPLBACKEND = "Agg"
# OpenCV headless configuration
OPENCV_IO_ENABLE_OPENEXR = "false"
OPENCV_IO_ENABLE_JASPER = "false"
# PaddleX configuration for production deployment
PADDLE_PDX_MODEL_SOURCE = "BOS"

[phases.setup]
# Install system packages needed for headless OpenCV and PaddleX
aptPkgs = [
    "libglib2.0-0",
    "libsm6",
    "libxext6", 
    "libxrender1",
    "libgomp1"
]

# Simple post-install verification (requirements.txt now handles the heavy lifting)
[phases.postInstall]
dependsOn = ["install"]  
cmds = [
    "echo '🔧 NIXPACKS: Verifying PaddleX OCR installation...'",
    # Remove any GUI OpenCV that might have been installed as dependencies
    ". /opt/venv/bin/activate && pip uninstall -y opencv-python opencv-contrib-python || echo 'No GUI OpenCV found'",
    # Ensure headless OpenCV is installed
    ". /opt/venv/bin/activate && pip install opencv-contrib-python-headless>=4.5.0 --force-reinstall",
    # Verify installation
    ". /opt/venv/bin/activate && python -c 'import cv2; print(f\"✅ OpenCV {cv2.__version__} verified\")' || echo '❌ OpenCV verification failed'",
    ". /opt/venv/bin/activate && python -c 'from paddlex import create_pipeline; print(\"✅ PaddleX OCR ready\")' || echo '❌ PaddleX verification failed'",
    "echo '✅ NIXPACKS: Installation verification completed'"
]

[start]
cmd = "python main.py"