[build]
providers = ["python"]

[build.env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
# Force headless mode for graphics libraries  
DISPLAY = ":99"
QT_QPA_PLATFORM = "offscreen"
MPLBACKEND = "Agg"
# OpenCV headless configuration
OPENCV_IO_ENABLE_OPENEXR = "0"
# Disable GUI-related imports
SDL_VIDEODRIVER = "dummy"

[phases.setup]
aptPkgs = [
    # Image processing libraries
    "libjpeg-dev",
    "libpng-dev", 
    "libtiff-dev",
    # OpenGL/Graphics libraries for headless OpenCV
    "libgl1-mesa-dev",
    "libglib2.0-0",
    "libsm6", 
    "libxext6",
    "libxrender-dev",
    "libgomp1",
    "libgthread-2.0-0",
    "libgtk-3-dev",
    # OpenCV video codec support
    "libavcodec-dev",
    "libavformat-dev",
    "libswscale-dev",
    # Additional graphics dependencies
    "libglu1-mesa-dev",
    "freeglut3-dev",
    "mesa-common-dev",
    # X11 libraries for headless display
    "libx11-6",
    "libxss1",
    "libgconf-2-4"
]


[start]
cmd = "python main.py"