[build]
providers = ["python"]

[build.env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
# Force headless mode for graphics libraries  
DISPLAY = ":99"
QT_QPA_PLATFORM = "offscreen"
MPLBACKEND = "Agg"
# OpenCV headless configuration
OPENCV_IO_ENABLE_OPENEXR = "0"
# Disable GUI-related imports
SDL_VIDEODRIVER = "dummy"

[phases.setup]
aptPkgs = [
    # Essential for libGL.so.1 error fix
    "libgl1",
    "libglib2.0-0",
    # Additional OpenGL/Mesa support for headless environments
    "libglx-mesa0",
    "libgl1-mesa-dri",
    # Basic X11 libraries for headless display
    "libsm6",
    "libxext6",
    "libxrender1"
]


[start]
cmd = "python main.py"