services:
  - type: web
    name: mkw-stats-bot
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
