services:
  - type: worker
    name: mkw-stats-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
    disk:
      name: mkw-stats-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
